[pytest]
python_files = tests/test_*.py
python_classes = Test*
python_functions = test_*

# Removed invalid flags
addopts = --html=reports/report.html --self-contained-html --alluredir=allure-results

markers =
    ui: Marks tests as UI tests
    login: Marks tests as login related
    smoke: For smoke tests
    regression: For regression tests

log_cli = true
log_cli_level = INFO